---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    fluxcd.io/tag.chart-image: semver:*
    fluxcd.io/automated: 'true'
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/schromTest/flux-get-started
    ref: master
    path: charts/ghost
  values:
    image:
      repository: gcr.io/github-action-example-project/static-site
      tag: 0.0.1
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
    mariadb:
      master:
        persistence:
          enabled: false
